server:
  port: 8090
---
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_first
    username: postgres
    password: Shkna1368


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
