server:
  port: 9090

spring:
  h2:
   console:
     path: "/h2"
     settings:
       trace: false
       web-allow-others: false
     enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_mvc
    username: postgres
    password: Shkna1368


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update