server:
  port: 2023

  spring:
    application:
      name: three-service # or "customer-service"
---
spring:
  boot:
   admin:
     api-path: /instances
     url: http://localhost:2023
     client:
       url: http://localhost:2023


---
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

---

logging:
  file:
    path: .
    name: mylog