server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_car_mg
    username: postgres
    password: Shkna1368


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ALL

  properties:
 
    hibernate:
      cache:
        use_second_level_cache: true
         region:
          factory_class=org:
            hibernate:
              cache:
                ehcache: EhCacheRegionFactory

