server:
  port: 9090

keycloak:
  principal-attribute: preferred_username
  auth-server-url: http://localhost:8080/auth
  realm: mapsa
  resource: mapsaapp

spring:
  security:
     oauth2:
       resourceserver:
         jwt:
           #jwk-set-uri : http://localhost:8080/auth/realms/mapsa/protocol/openid-connect/certs
           issuer-uri : http://localhost:8080/auth/realms/mapsa
