server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_store
    username: postgres
    password: Shkna1368


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true


---
logging:
  file:
    path: .
    name: mylog

---
spring:
  application:
    name: three-service # or "customer-service"
---
spring:
  boot:
    admin:
      api-path: /instances
      url: http://localhost:9090
      client:
        url: http://localhost:9090


---
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
