server:
  port: 2023

  spring:
    application:
      name: three-service # or "customer-service"
---
spring:
  boot:
   admin:
     api-path: /instances
     url: http://localhost:2023
     client:
       url: http://localhost:2023


---
management:
  security:
    enabled: false
  endpoints:
   web:
    exposure:
     include: "*"
   health:
    show-details: always
